# Given code
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    # Answer
    t = tuple(integer_list)
    print(hash(t))

# This solution is logically correct for Python 3.
# HackerRank's test case for this specific problem (Basic Data Types - Tuples)
# expects a hash value generated by Python 2, which differs from the Python 3 hash.
# The code is marked as "Wrong Answer" due to this platform incompatibility, not a logic error.
# If you try against a custom input exactly same as HackerRank, it will be successful.